#!/usr/bin/env python3
"""Compile the supplied custom SNES Arwing; no cartridge assets."""
import argparse
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
def number(v):
    return f'{float(v):.9f}F'
lines = ['// Generated by tools/generate_cockpit_assets.py from the supplied custom SNES Arwing.',
         'namespace starfox::vr::cockpit_assets {']
# Supplied custom mesh: tessellation/palette sampling is an offline import step.
arwing = json.loads((root / 'assets/vr/arwing-snes/geometry.json').read_text())
lines += ['struct ArwingTriangle {std::array<std::array<float,3>,3> points; uint32_t rgb;};',
          'inline constexpr ArwingTriangle arwing[]{']
for module in arwing['modules']:
    lines.append('// ' + module['name'])
    for triangle in module['triangles']:
        points = [module['vertices_obj'][i] for i in triangle['indices']]
        r, g, b = triangle['rgb']
        lines.append('    {{{{' + '},{'.join(','.join(number(v) for v in p) for p in points)
                     + '}}},' + f'0x{r:02x}{g:02x}{b:02x}U' + '},')
lines += ['};', 'inline constexpr std::array<std::array<float,3>,2> arwing_edges[]{']
for module in arwing['modules']:
    for edge in module['edges']:
        points = [module['vertices_obj'][i] for i in edge]
        if points[0] != points[1]:
            lines.append('    {{{' + '},{'.join(','.join(number(v) for v in p) for p in points) + '}}},')
lines += ['};', '}']
text = '\n'.join(lines) + '\n'
output = root / 'src/vr/cockpit_assets.inc'
parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
if args.check:
    if output.read_text() != text: raise SystemExit('Cockpit assets are stale; run tools/generate_cockpit_assets.py')
else: output.write_text(text)
